FROM python:3.9-slim-buster
WORKDIR /usr/local/my_app
COPY ./docker_app ./
RUN apt update && \
    apt install gcc python3-dev -y libpq-dev -y && \
    pip install -r ./requirements.txt
CMD ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5000"]
EXPOSE 5000
