FROM python:3.8-slim-buster
WORKDIR /usr/src/subscriber
COPY ./subscriber /usr/src/subscriber
COPY ./requirements.txt /usr/src/subscriber/requirements.txt
RUN apt update && \
    apt install gcc python3-dev -y libpq-dev -y
RUN pip install -r ./requirements.txt
CMD [ "python3", "app.py"]