version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: rails
      POSTGRES_USER: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # web:
  #   build: .
  #   volumes:
  #     - .:/hryhorchuk_app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
